name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Clone
        run: 'git clone https://github.com/pmh-only/blockchain.git /home/runner/go/src/github.com/pmh-only/blockchain'

      - name: Build
        run: go build -v /home/runner/go/src/github.com/pmh-only/blockchain
        working-directory: /home/runner/go/src/github.com/pmh-only/blockchain

      - name: Test
        run: go test -v /home/runner/go/src/github.com/pmh-only/blockchain/src
        working-directory: /home/runner/go/src/github.com/pmh-only/blockchain
